"""well_id

Revision ID: d202bad2039f
Revises: f28c74842697
Create Date: 2023-01-24 15:47:12.116771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd202bad2039f'
down_revision = 'f28c74842697'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vlp', sa.Column('well_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vlp', 'well_data', ['well_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vlp', type_='foreignkey')
    op.drop_column('vlp', 'well_id')
    # ### end Alembic commands ###
